%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_DEFK17_rep';
M_.dynare_version = '5.1';
oo_.dynare_version = '5.1';
options_.dynare_version = '5.1';
%
% Some global variables initialization
%
global_initialization;
options_.nograph = true;
M_.exo_names = cell(1,1);
M_.exo_names_tex = cell(1,1);
M_.exo_names_long = cell(1,1);
M_.exo_names(1) = {'e_phi'};
M_.exo_names_tex(1) = {'e\_phi'};
M_.exo_names_long(1) = {'e_phi'};
M_.endo_names = cell(33,1);
M_.endo_names_tex = cell(33,1);
M_.endo_names_long = cell(33,1);
M_.endo_names(1) = {'C'};
M_.endo_names_tex(1) = {'C'};
M_.endo_names_long(1) = {'C'};
M_.endo_names(2) = {'Inv'};
M_.endo_names_tex(2) = {'Inv'};
M_.endo_names_long(2) = {'Inv'};
M_.endo_names(3) = {'S_Inv'};
M_.endo_names_tex(3) = {'S\_Inv'};
M_.endo_names_long(3) = {'S_Inv'};
M_.endo_names(4) = {'dS_Inv'};
M_.endo_names_tex(4) = {'dS\_Inv'};
M_.endo_names_long(4) = {'dS_Inv'};
M_.endo_names(5) = {'H'};
M_.endo_names_tex(5) = {'H'};
M_.endo_names_long(5) = {'H'};
M_.endo_names(6) = {'Y'};
M_.endo_names_tex(6) = {'Y'};
M_.endo_names_long(6) = {'Y'};
M_.endo_names(7) = {'tau'};
M_.endo_names_tex(7) = {'tau'};
M_.endo_names_long(7) = {'tau'};
M_.endo_names(8) = {'K'};
M_.endo_names_tex(8) = {'K'};
M_.endo_names_long(8) = {'K'};
M_.endo_names(9) = {'N'};
M_.endo_names_tex(9) = {'N'};
M_.endo_names_long(9) = {'N'};
M_.endo_names(10) = {'Ng'};
M_.endo_names_tex(10) = {'Ng'};
M_.endo_names_long(10) = {'Ng'};
M_.endo_names(11) = {'LY'};
M_.endo_names_tex(11) = {'LY'};
M_.endo_names_long(11) = {'LY'};
M_.endo_names(12) = {'QK'};
M_.endo_names_tex(12) = {'QK'};
M_.endo_names_long(12) = {'QK'};
M_.endo_names(13) = {'GDP'};
M_.endo_names_tex(13) = {'GDP'};
M_.endo_names_long(13) = {'GDP'};
M_.endo_names(14) = {'R'};
M_.endo_names_tex(14) = {'R'};
M_.endo_names_long(14) = {'R'};
M_.endo_names(15) = {'Q'};
M_.endo_names_tex(15) = {'Q'};
M_.endo_names_long(15) = {'Q'};
M_.endo_names(16) = {'pI'};
M_.endo_names_tex(16) = {'pI'};
M_.endo_names_long(16) = {'pI'};
M_.endo_names(17) = {'RK'};
M_.endo_names_tex(17) = {'RK'};
M_.endo_names_long(17) = {'RK'};
M_.endo_names(18) = {'rK'};
M_.endo_names_tex(18) = {'rK'};
M_.endo_names_long(18) = {'rK'};
M_.endo_names(19) = {'rr'};
M_.endo_names_tex(19) = {'rr'};
M_.endo_names_long(19) = {'rr'};
M_.endo_names(20) = {'rr0'};
M_.endo_names_tex(20) = {'rr0'};
M_.endo_names_long(20) = {'rr0'};
M_.endo_names(21) = {'ERQ'};
M_.endo_names_tex(21) = {'ERQ'};
M_.endo_names_long(21) = {'ERQ'};
M_.endo_names(22) = {'w'};
M_.endo_names_tex(22) = {'w'};
M_.endo_names_long(22) = {'w'};
M_.endo_names(23) = {'infl_w'};
M_.endo_names_tex(23) = {'infl\_w'};
M_.endo_names_long(23) = {'infl_w'};
M_.endo_names(24) = {'X1w'};
M_.endo_names_tex(24) = {'X1w'};
M_.endo_names_long(24) = {'X1w'};
M_.endo_names(25) = {'X2w'};
M_.endo_names_tex(25) = {'X2w'};
M_.endo_names_long(25) = {'X2w'};
M_.endo_names(26) = {'mc'};
M_.endo_names_tex(26) = {'mc'};
M_.endo_names_long(26) = {'mc'};
M_.endo_names(27) = {'infl'};
M_.endo_names_tex(27) = {'infl'};
M_.endo_names_long(27) = {'infl'};
M_.endo_names(28) = {'X1p'};
M_.endo_names_tex(28) = {'X1p'};
M_.endo_names_long(28) = {'X1p'};
M_.endo_names(29) = {'X2p'};
M_.endo_names_tex(29) = {'X2p'};
M_.endo_names_long(29) = {'X2p'};
M_.endo_names(30) = {'Delta_p'};
M_.endo_names_tex(30) = {'Delta\_p'};
M_.endo_names_long(30) = {'Delta_p'};
M_.endo_names(31) = {'CY'};
M_.endo_names_tex(31) = {'CY'};
M_.endo_names_long(31) = {'CY'};
M_.endo_names(32) = {'Spr'};
M_.endo_names_tex(32) = {'Spr'};
M_.endo_names_long(32) = {'Spr'};
M_.endo_names(33) = {'phi'};
M_.endo_names_tex(33) = {'phi'};
M_.endo_names_long(33) = {'phi'};
M_.endo_partitions = struct();
M_.param_names = cell(34,1);
M_.param_names_tex = cell(34,1);
M_.param_names_long = cell(34,1);
M_.param_names(1) = {'beta'};
M_.param_names_tex(1) = {'beta'};
M_.param_names_long(1) = {'beta'};
M_.param_names(2) = {'sigma'};
M_.param_names_tex(2) = {'sigma'};
M_.param_names_long(2) = {'sigma'};
M_.param_names(3) = {'nu'};
M_.param_names_tex(3) = {'nu'};
M_.param_names_long(3) = {'nu'};
M_.param_names(4) = {'kappa'};
M_.param_names_tex(4) = {'kappa'};
M_.param_names_long(4) = {'kappa'};
M_.param_names(5) = {'theta'};
M_.param_names_tex(5) = {'theta'};
M_.param_names_long(5) = {'theta'};
M_.param_names(6) = {'gamma'};
M_.param_names_tex(6) = {'gamma'};
M_.param_names_long(6) = {'gamma'};
M_.param_names(7) = {'Gamma'};
M_.param_names_tex(7) = {'Gamma'};
M_.param_names_long(7) = {'Gamma'};
M_.param_names(8) = {'delta'};
M_.param_names_tex(8) = {'delta'};
M_.param_names_long(8) = {'delta'};
M_.param_names(9) = {'s0'};
M_.param_names_tex(9) = {'s0'};
M_.param_names_long(9) = {'s0'};
M_.param_names(10) = {'lambda_w'};
M_.param_names_tex(10) = {'lambda\_w'};
M_.param_names_long(10) = {'lambda_w'};
M_.param_names(11) = {'lambda_p'};
M_.param_names_tex(11) = {'lambda\_p'};
M_.param_names_long(11) = {'lambda_p'};
M_.param_names(12) = {'xi_w'};
M_.param_names_tex(12) = {'xi\_w'};
M_.param_names_long(12) = {'xi_w'};
M_.param_names(13) = {'xi_p'};
M_.param_names_tex(13) = {'xi\_p'};
M_.param_names_long(13) = {'xi_p'};
M_.param_names(14) = {'psi_p'};
M_.param_names_tex(14) = {'psi\_p'};
M_.param_names_long(14) = {'psi_p'};
M_.param_names(15) = {'psi_y'};
M_.param_names_tex(15) = {'psi\_y'};
M_.param_names_long(15) = {'psi_y'};
M_.param_names(16) = {'rho_i'};
M_.param_names_tex(16) = {'rho\_i'};
M_.param_names_long(16) = {'rho_i'};
M_.param_names(17) = {'psi_k'};
M_.param_names_tex(17) = {'psi\_k'};
M_.param_names_long(17) = {'psi_k'};
M_.param_names(18) = {'psi_tau'};
M_.param_names_tex(18) = {'psi\_tau'};
M_.param_names_long(18) = {'psi_tau'};
M_.param_names(19) = {'rho_phi'};
M_.param_names_tex(19) = {'rho\_phi'};
M_.param_names_long(19) = {'rho_phi'};
M_.param_names(20) = {'Y_ss'};
M_.param_names_tex(20) = {'Y\_ss'};
M_.param_names_long(20) = {'Y_ss'};
M_.param_names(21) = {'C_ss'};
M_.param_names_tex(21) = {'C\_ss'};
M_.param_names_long(21) = {'C_ss'};
M_.param_names(22) = {'I_ss'};
M_.param_names_tex(22) = {'I\_ss'};
M_.param_names_long(22) = {'I_ss'};
M_.param_names(23) = {'K_ss'};
M_.param_names_tex(23) = {'K\_ss'};
M_.param_names_long(23) = {'K_ss'};
M_.param_names(24) = {'H_ss'};
M_.param_names_tex(24) = {'H\_ss'};
M_.param_names_long(24) = {'H_ss'};
M_.param_names(25) = {'R_ss'};
M_.param_names_tex(25) = {'R\_ss'};
M_.param_names_long(25) = {'R_ss'};
M_.param_names(26) = {'Q_ss'};
M_.param_names_tex(26) = {'Q\_ss'};
M_.param_names_long(26) = {'Q_ss'};
M_.param_names(27) = {'RK_ss'};
M_.param_names_tex(27) = {'RK\_ss'};
M_.param_names_long(27) = {'RK_ss'};
M_.param_names(28) = {'rK_ss'};
M_.param_names_tex(28) = {'rK\_ss'};
M_.param_names_long(28) = {'rK_ss'};
M_.param_names(29) = {'w_ss'};
M_.param_names_tex(29) = {'w\_ss'};
M_.param_names_long(29) = {'w_ss'};
M_.param_names(30) = {'tau_ss'};
M_.param_names_tex(30) = {'tau\_ss'};
M_.param_names_long(30) = {'tau_ss'};
M_.param_names(31) = {'LY_ss'};
M_.param_names_tex(31) = {'LY\_ss'};
M_.param_names_long(31) = {'LY_ss'};
M_.param_names(32) = {'A_ss'};
M_.param_names_tex(32) = {'A\_ss'};
M_.param_names_long(32) = {'A_ss'};
M_.param_names(33) = {'phi_ss'};
M_.param_names_tex(33) = {'phi\_ss'};
M_.param_names_long(33) = {'phi_ss'};
M_.param_names(34) = {'shock_val'};
M_.param_names_tex(34) = {'shock\_val'};
M_.param_names_long(34) = {'shock_val'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 1;
M_.endo_nbr = 33;
M_.param_nbr = 34;
M_.orig_endo_nbr = 33;
M_.aux_vars = [];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(1, 1);
M_.Correlation_matrix = eye(1, 1);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.orig_eq_nbr = 33;
M_.eq_nbr = 33;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 10 43;
 0 11 0;
 0 12 0;
 0 13 0;
 0 14 0;
 1 15 0;
 0 16 0;
 2 17 0;
 3 18 0;
 4 19 0;
 5 20 0;
 0 21 0;
 0 22 0;
 6 23 0;
 0 24 44;
 0 25 45;
 0 26 46;
 0 27 0;
 0 28 0;
 0 29 0;
 0 30 0;
 7 31 0;
 0 32 47;
 0 33 48;
 0 34 49;
 0 35 0;
 0 36 50;
 0 37 51;
 0 38 52;
 8 39 0;
 0 40 0;
 0 41 0;
 9 42 53;]';
M_.nstatic = 14;
M_.nfwrd   = 10;
M_.npred   = 8;
M_.nboth   = 1;
M_.nsfwrd   = 11;
M_.nspred   = 9;
M_.ndynamic   = 19;
M_.dynamic_tmp_nbr = [29; 10; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , '1' ;
  2 , 'name' , '2' ;
  3 , 'name' , '3' ;
  4 , 'name' , 'pI' ;
  5 , 'name' , 'S_Inv' ;
  6 , 'name' , 'dS_Inv' ;
  7 , 'name' , '7' ;
  8 , 'name' , 'rK' ;
  9 , 'name' , 'w' ;
  10 , 'name' , '10' ;
  11 , 'name' , 'K' ;
  12 , 'name' , '12' ;
  13 , 'name' , 'X1p' ;
  14 , 'name' , '14' ;
  15 , 'name' , 'X2p' ;
  16 , 'name' , 'X1w' ;
  17 , 'name' , '17' ;
  18 , 'name' , 'X2w' ;
  19 , 'name' , '19' ;
  20 , 'name' , 'Delta_p' ;
  21 , 'name' , 'R' ;
  22 , 'name' , 'Ng' ;
  23 , 'name' , 'tau' ;
  24 , 'name' , '24' ;
  25 , 'name' , 'Y' ;
  26 , 'name' , 'rr' ;
  27 , 'name' , 'ERQ' ;
  28 , 'name' , 'Spr' ;
  29 , 'name' , 'CY' ;
  30 , 'name' , 'QK' ;
  31 , 'name' , 'GDP' ;
  32 , 'name' , '32' ;
  33 , 'name' , 'phi' ;
};
M_.mapping.C.eqidx = [1 2 14 15 18 25 31 32 ];
M_.mapping.Inv.eqidx = [3 4 5 6 10 12 25 31 ];
M_.mapping.S_Inv.eqidx = [4 5 10 25 ];
M_.mapping.dS_Inv.eqidx = [4 6 ];
M_.mapping.H.eqidx = [7 8 9 10 17 18 ];
M_.mapping.Y.eqidx = [3 7 10 14 15 21 23 24 25 ];
M_.mapping.tau.eqidx = [3 23 24 ];
M_.mapping.K.eqidx = [7 8 9 10 11 12 30 ];
M_.mapping.N.eqidx = [3 11 ];
M_.mapping.Ng.eqidx = [11 22 23 24 ];
M_.mapping.LY.eqidx = [3 23 24 ];
M_.mapping.QK.eqidx = [30 ];
M_.mapping.GDP.eqidx = [31 ];
M_.mapping.R.eqidx = [3 21 23 24 26 ];
M_.mapping.Q.eqidx = [1 2 3 23 24 27 29 30 ];
M_.mapping.pI.eqidx = [1 2 3 4 10 29 31 ];
M_.mapping.RK.eqidx = [2 3 10 24 27 ];
M_.mapping.rK.eqidx = [8 ];
M_.mapping.rr.eqidx = [1 26 28 ];
M_.mapping.rr0.eqidx = [32 ];
M_.mapping.ERQ.eqidx = [27 28 ];
M_.mapping.w.eqidx = [9 10 18 19 ];
M_.mapping.infl_w.eqidx = [16 17 18 19 ];
M_.mapping.X1w.eqidx = [16 17 ];
M_.mapping.X2w.eqidx = [16 18 ];
M_.mapping.mc.eqidx = [8 9 14 ];
M_.mapping.infl.eqidx = [3 13 14 15 19 20 21 23 24 26 ];
M_.mapping.X1p.eqidx = [13 14 ];
M_.mapping.X2p.eqidx = [13 15 ];
M_.mapping.Delta_p.eqidx = [7 20 ];
M_.mapping.CY.eqidx = [29 ];
M_.mapping.Spr.eqidx = [28 ];
M_.mapping.phi.eqidx = [2 3 22 33 ];
M_.mapping.e_phi.eqidx = [33 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [6 8 9 10 11 14 22 30 33 ];
M_.exo_names_orig_ord = [1:1];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(33, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(1, 1);
M_.params = NaN(34, 1);
M_.endo_trends = struct('deflator', cell(33, 1), 'log_deflator', cell(33, 1), 'growth_factor', cell(33, 1), 'log_growth_factor', cell(33, 1));
M_.NNZDerivatives = [145; -1; -1; ];
M_.static_tmp_nbr = [22; 10; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
close all;
M_.params(1) = 0.99347;
beta = M_.params(1);
M_.params(2) = 1;
sigma = M_.params(2);
M_.params(3) = 1;
nu = M_.params(3);
M_.params(5) = 0.79246;
theta = M_.params(5);
M_.params(4) = 0.009486;
kappa = M_.params(4);
M_.params(8) = 0.024291;
delta = M_.params(8);
M_.params(6) = 0.34002;
gamma = M_.params(6);
M_.params(9) = 0.75;
s0 = M_.params(9);
M_.params(13) = 0.75;
xi_p = M_.params(13);
M_.params(12) = 0.75;
xi_w = M_.params(12);
M_.params(11) = 0.1;
lambda_p = M_.params(11);
M_.params(10) = 0.1;
lambda_w = M_.params(10);
M_.params(14) = 1.5;
psi_p = M_.params(14);
M_.params(15) = 0.125;
psi_y = M_.params(15);
M_.params(16) = 0;
rho_i = M_.params(16);
M_.params(18) = 0.1;
psi_tau = M_.params(18);
M_.params(25) = 1.0055;
R_ss = M_.params(25);
M_.params(32) = 1;
A_ss = M_.params(32);
M_.params(33) = 0.3092;
phi_ss = M_.params(33);
M_.params(31) = 1.6;
LY_ss = M_.params(31);
M_.params(20) = 2.6779;
Y_ss = M_.params(20);
M_.params(23) = 29.2064;
K_ss = M_.params(23);
M_.params(24) = 0.90345;
H_ss = M_.params(24);
M_.params(22) = 0.70945;
I_ss = M_.params(22);
M_.params(21) = 1.9685;
C_ss = M_.params(21);
M_.params(26) = 1.0223;
Q_ss = M_.params(26);
M_.params(27) = 0.031176;
RK_ss = M_.params(27);
M_.params(28) = 0.031176;
rK_ss = M_.params(28);
CY_ss=0.0011116;
M_.params(29) = 1.9563;
w_ss = M_.params(29);
M_.params(30) = 0.023387;
tau_ss = M_.params(30);
KY_ratio=10.9064;
KH_ratio=32.3277;
IY_ratio=0.26493;
CY_ratio=0.73507;
M_.params(7) = 0.26779;
Gamma = M_.params(7);
M_.params(17) = (-4.8066);
psi_k = M_.params(17);
M_.params(34) = (-0.218);
shock_val = M_.params(34);
M_.params(19) = 0.984;
rho_phi = M_.params(19);
GE=1;
%
% INITVAL instructions
%
options_.initval_file = false;
oo_.steady_state(1) = M_.params(21);
oo_.steady_state(2) = M_.params(22);
oo_.steady_state(3) = 0;
oo_.steady_state(4) = 0;
oo_.steady_state(5) = M_.params(24);
oo_.steady_state(6) = M_.params(20);
oo_.steady_state(11) = M_.params(31);
oo_.steady_state(7) = M_.params(30);
oo_.steady_state(8) = M_.params(23);
oo_.steady_state(9) = M_.params(23);
oo_.steady_state(10) = 0;
oo_.steady_state(14) = M_.params(25);
oo_.steady_state(19) = M_.params(25);
oo_.steady_state(20) = M_.params(25)*(1+CY_ss);
oo_.steady_state(21) = M_.params(27)/M_.params(26)+1-M_.params(8);
oo_.steady_state(32) = oo_.steady_state(21)-oo_.steady_state(19);
oo_.steady_state(15) = M_.params(26);
oo_.steady_state(16) = 1;
oo_.steady_state(17) = M_.params(27);
oo_.steady_state(18) = M_.params(28);
oo_.steady_state(31) = CY_ss;
oo_.steady_state(22) = M_.params(29);
oo_.steady_state(23) = 1;
oo_.steady_state(24) = (1+M_.params(10))*M_.params(24)^(1+M_.params(3))/(1-M_.params(1)*M_.params(12));
oo_.steady_state(25) = M_.params(24)*M_.params(29)*M_.params(21)^(-M_.params(2))/(1-M_.params(1)*M_.params(12));
oo_.steady_state(26) = 1/(1+M_.params(11));
oo_.steady_state(27) = 1;
oo_.steady_state(28) = M_.params(20)*M_.params(21)^(-M_.params(2))/(1-M_.params(1)*M_.params(13));
oo_.steady_state(29) = M_.params(20)*M_.params(21)^(-M_.params(2))/(1-M_.params(1)*M_.params(13));
oo_.steady_state(30) = 1;
oo_.steady_state(33) = M_.params(33);
oo_.exo_steady_state(1) = 0;
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
options_.solve_algo = 2;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.noprint = true;
options_.order = 1;
options_.periods = 300;
var_list_ = {};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'NK_DEFK17_rep_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_DEFK17_rep_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_DEFK17_rep_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_DEFK17_rep_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_DEFK17_rep_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_DEFK17_rep_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_DEFK17_rep_results.mat'], 'oo_recursive_', '-append');
end
disp('Note: 1 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
